version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seu_banco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    volumes:
      - ./mysql-data:/var/lib/mysql
